server/config/routes.rb
Rails.application.routes.draw do
  resources :cards
  resources :lists
  resources :boards
  resources :members
  resources :groups
  resources :users
  # jsonapi_resources :users

  post 'user_token' => 'user_token#create'
  root :to => 'home#index'
end

server/app/models/board.rb
# == Schema Information
#
# Table name: boards
#
#  id                :integer          not null, primary key
#  board_description :string           default("")
#  board_name        :string(20)       default(""), not null
#  position          :integer
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#  group_id          :integer
#  user_id           :integer
#
# Indexes
#
#  index_boards_on_group_id  (group_id)
#  index_boards_on_user_id   (user_id)
#

class Board < ApplicationRecord
  acts_as_list

  belongs_to :user
  belongs_to :group
  has_many :lists, ->{ order(position: :asc) }, dependent: :destroy

  validates :board_name, :presence => true, length: { maximum: 20 }
end

server/app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :set_board, only: [:show, :edit, :update, :destroy]

  # GET /boards
  # GET /boards.json
  def index
    @boards = Board.all
  end

  # GET /boards/1
  # GET /boards/1.json
  def show
  end

  # GET /boards/new
  def new
    @board = Board.new
  end

  # GET /boards/1/edit
  def edit
  end

  # POST /boards
  # POST /boards.json
  def create
    @board = Board.new(board_params)

    respond_to do |format|
      if @board.save
        format.html { redirect_to @board, notice: 'Board was successfully created.' }
        format.json { render :show, status: :created, location: @board }
      else
        format.html { render :new }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /boards/1
  # PATCH/PUT /boards/1.json
  def update
    respond_to do |format|
      if @board.update(board_params)
        format.html { redirect_to @board, notice: 'Board was successfully updated.' }
        format.json { render :show, status: :ok, location: @board }
      else
        format.html { render :edit }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /boards/1
  # DELETE /boards/1.json
  def destroy
    @board.destroy
    respond_to do |format|
      format.html { redirect_to boards_url, notice: 'Board was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_board
      @board = Board.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def board_params
      params.require(:board).permit(:board_name, :board_description, :user_id, :group_id, :position)
    end
end

server/app/views/boards/_form.html.erb
<%= form_with(model: board, local: true) do |form| %>
  <% if board.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(board.errors.count, "error") %> prohibited this board from being saved:</h2>

      <ul>
      <% board.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :board_name %>
    <%= form.text_field :board_name %>
  </div>

  <div class="field">
    <%= form.label :board_description %>
    <%= form.text_field :board_description %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :group_id %>
    <%= form.text_field :group_id %>
  </div>

  <div class="field">
    <%= form.label :position %>
    <%= form.number_field :position %>
  </div>

  <div class="actions">
    <%= form.submit class: "btn" %>
  </div>
<% end %>

server/app/views/boards/edit.html.erb
<h1>Editing Board</h1>

<%= render 'form', board: @board %>

<%= link_to 'Show', @board %> |
<%= link_to 'Back', boards_path %>

server/app/views/boards/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Boards</h1>

<table>
  <thead>
    <tr>
      <th>Board name</th>
      <th>Board description</th>
      <th>User</th>
      <th>Group</th>
      <th>Position</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @boards.each do |board| %>
      <tr>
        <td><%= board.board_name %></td>
        <td><%= board.board_description %></td>
        <td><%= board.user %></td>
        <td><%= board.group %></td>
        <td><%= board.position %></td>
        <td><%= link_to 'Show', board %></td>
        <td><%= link_to 'Edit', edit_board_path(board) %></td>
        <td><%= link_to 'Destroy', board, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Board', new_board_path %>

server/app/views/boards/new.html.erb
<h1>New Board</h1>

<%= render 'form', board: @board %>

<%= link_to 'Back', boards_path %>

server/app/views/boards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Board name:</strong>
  <%= @board.board_name %>
</p>

<p>
  <strong>Board description:</strong>
  <%= @board.board_description %>
</p>

<p>
  <strong>User:</strong>
  <%= @board.user %>
</p>

<p>
  <strong>Group:</strong>
  <%= @board.group %>
</p>

<p>
  <strong>Position:</strong>
  <%= @board.position %>
</p>

<%= link_to 'Edit', edit_board_path(@board) %> |
<%= link_to 'Back', boards_path %>