server/config/routes.rb
Rails.application.routes.draw do
  resources :cards
  resources :lists
  resources :boards
  resources :members
  resources :groups
  resources :users
  # jsonapi_resources :users

  post 'user_token' => 'user_token#create'
  root :to => 'home#index'
end

server/app/models/list.rb
# == Schema Information
#
# Table name: lists
#
#  id               :integer          not null, primary key
#  list_description :string           default("")
#  list_name        :string(20)       default(""), not null
#  position         :integer
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  board_id         :integer
#
# Indexes
#
#  index_lists_on_board_id  (board_id)
#

class List < ApplicationRecord
  acts_as_list scope: :board

  belongs_to :board
  has_many :cards, ->{ order(position: :asc) }, dependent: :destroy

  validates :list_name, :presence => true, length: { maximum: 20 }
end

server/app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :edit, :update, :destroy]

  # GET /lists
  # GET /lists.json
  def index
    @lists = List.all
  end

  # GET /lists/1
  # GET /lists/1.json
  def show
  end

  # GET /lists/new
  def new
    @list = List.new
  end

  # GET /lists/1/edit
  def edit
  end

  # POST /lists
  # POST /lists.json
  def create
    @list = List.new(list_params)

    respond_to do |format|
      if @list.save
        format.html { redirect_to @list, notice: 'List was successfully created.' }
        format.json { render :show, status: :created, location: @list }
      else
        format.html { render :new }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lists/1
  # PATCH/PUT /lists/1.json
  def update
    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to @list, notice: 'List was successfully updated.' }
        format.json { render :show, status: :ok, location: @list }
      else
        format.html { render :edit }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1
  # DELETE /lists/1.json
  def destroy
    @list.destroy
    respond_to do |format|
      format.html { redirect_to lists_url, notice: 'List was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = List.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def list_params
      params.require(:list).permit(:list_name, :list_description, :board_id, :position)
    end
end

server/app/views/lists/_form.html.erb
<%= form_with(model: list, local: true) do |form| %>
  <% if list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
      <% list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :list_name %>
    <%= form.text_field :list_name %>
  </div>

  <div class="field">
    <%= form.label :list_description %>
    <%= form.text_field :list_description %>
  </div>

  <div class="field">
    <%= form.label :board_id %>
    <%= form.text_field :board_id %>
  </div>

  <div class="field">
    <%= form.label :position %>
    <%= form.number_field :position %>
  </div>

  <div class="actions">
    <%= form.submit class: "btn" %>
  </div>
<% end %>

server/app/views/lists/edit.html.erb
<h1>Editing List</h1>

<%= render 'form', list: @list %>

<%= link_to 'Show', @list %> |
<%= link_to 'Back', lists_path %>

server/app/views/lists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lists</h1>

<table>
  <thead>
    <tr>
      <th>List name</th>
      <th>List description</th>
      <th>Board</th>
      <th>Position</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lists.each do |list| %>
      <tr>
        <td><%= list.list_name %></td>
        <td><%= list.list_description %></td>
        <td><%= list.board %></td>
        <td><%= list.position %></td>
        <td><%= link_to 'Show', list %></td>
        <td><%= link_to 'Edit', edit_list_path(list) %></td>
        <td><%= link_to 'Destroy', list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New List', new_list_path %>

server/app/views/lists/new.html.erb
<h1>New List</h1>

<%= render 'form', list: @list %>

<%= link_to 'Back', lists_path %>

server/app/views/lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>List name:</strong>
  <%= @list.list_name %>
</p>

<p>
  <strong>List description:</strong>
  <%= @list.list_description %>
</p>

<p>
  <strong>Board:</strong>
  <%= @list.board %>
</p>

<p>
  <strong>Position:</strong>
  <%= @list.position %>
</p>

<%= link_to 'Edit', edit_list_path(@list) %> |
<%= link_to 'Back', lists_path %>