server/config/routes.rb
Rails.application.routes.draw do
  resources :cards
  resources :lists
  resources :boards
  resources :members
  resources :groups
  resources :users
  # jsonapi_resources :users

  post 'user_token' => 'user_token#create'
  root :to => 'home#index'
end

server/app/views/layouts/application.html.erb
<!doctype html>
<html lang="en" class="rykn0wxx no-js">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="author" content="rykn0wxx" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui" />

    <title><%= content_for?(:title) ? yield(:title) + " | rykn0wxx" : "rykn0wxx" %></title>

    <%= javascript_tag type: "text/javascript" do -%>
    document.documentElement.className = "rykn0wxx js";
    <% end -%>

    <%= tag :meta, name: 'turbolinks-root', content: '/' %>
    <%= tag :meta, name: 'turbolinks-cache-control', content: 'no-preview' %>
    <%= tag :meta, name: 'turbolinks-visit-control', content: 'reload' %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', 'data-turbolinks-track': 'reload', media: 'all' %>
  </head>

  <body class="mudhead">

    <header class="mb-8 shadow-lg">
      <nav class="flex items-center justify-between flex-wrap bg-gray-100 py-3 lg:px-10 px-3 text-gray-700 border-b border-gray-400">
        <div class="flex items-center flex-no-shrink mr-6">
          <%= link_to "FullApp", root_path, class:"transition tracking-wide font-semibold" %>
        </div>
        <div class="block lg:hidden">
          <button class="flex items-center px-3 py-2 border rounded text-grey border-gray-500 hover:text-gray-600 hover:border-gray-600">
            <svg class="fill-current h-3 w-3" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><title>Menu</title><path d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z"/></svg>
          </button>
        </div>
        <div class="w-full block lg:flex-1 lg:flex items-center text-center lg:text-left">

          <div class="w-full block lg:flex lg:flex-row lg:flex-1 mt-2 lg:mt-0 text-center lg:text-left lg:justify-end">
            <%= link_to 'Users', users_path, class: "transition text-gray-500 font-semibold py-2 px-4 rounded cursor-pointer hover:text-blue-800" %>
            <%= link_to 'Groups', groups_path, class: "transition text-gray-500 font-semibold py-2 px-4 rounded cursor-pointer hover:text-blue-800" %>
            <%= link_to 'Members', members_path, class: "transition text-gray-500 font-semibold py-2 px-4 rounded cursor-pointer hover:text-blue-800" %>
            <%= link_to 'Boards', boards_path, class: "transition text-gray-500 font-semibold py-2 px-4 rounded cursor-pointer hover:text-blue-800" %>
            <%= link_to 'Lists', lists_path, class: "transition text-gray-500 font-semibold py-2 px-4 rounded cursor-pointer hover:text-blue-800" %>
            <%= link_to 'Cards', cards_path, class: "transition text-gray-500 font-semibold py-2 px-4 rounded cursor-pointer hover:text-blue-800" %>
          </div>
        </div>
      </nav>
    </header>

    <main class="lg:px-10 px-4">
      <%= yield %>
    </main>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload', 'data-turbolinks-suppress-warning': 'true' %>
  </body>
</html>